version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: olx_price_monitor
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: olx_user
      MYSQL_PASSWORD: olx_secret
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

    networks:
      - app-network

  php-worker:
    build: .
    command: ["wait-for-it.sh", "db:3306", "--", "php", "/app/worker.php"]
    environment:
      - WORKER_INTERVAL=3600
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db

  test:
    build: .
    working_dir: /app
    entrypoint: ["wait-for-it.sh", "db:3306", "--", "./vendor/bin/phpunit"]
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
